[package]
name = "fractal"
version = "0.1.0"
authors = ["Arden Rasmussen <ardenisthebest@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = '*'
num = "*"
rayon = "*"
clap = "*"
